#!/bin/sh

set -e
commit="$(git rev-parse HEAD)"
commit_short="$(git rev-parse --short HEAD)"
build_time="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
version="$(git describe --tags HEAD)"

if git diff-index --exit-code --quiet HEAD --; then
	dirty="-dirty"
else
	dirty=""
fi

# It is a real release if tagged (we don't tag.... yet :)
if git rev-parse --verify --quiet refs/tags/"$version" >/dev/null; then
	gitweb_url="https://github.com/sysadminsmedia/homebox/releases/tag/$version"
else
	gitweb_url="https://github.com/rapidcow/homebox/tree/$commit"
fi


set -x
cd build/backend
CGO_ENABLED=0 go build -ldflags "-s -w
	-X main.commit=$commit_short
	-X main.buildTime=$build_time
	-X main.version=$version-$dirty
	-X main.gitwebUrl=$gitweb_url
" -o bin/api -v app/api/*.go
